name: CI

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Validate index.html
        uses: ./.github/actions/validate-html
