name: CI

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Validate index.html
        run: |
          docker run --rm \
            -v "$PWD:/data:ro" \
            ghcr.io/validator/validator:latest \
            vnu --skip-non-html /data/index.html
